services:
  - type: web
    name: cycloneai
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SERVE_STATIC_SPA
        value: "True"
      - key: HOST
        value: 0.0.0.0
